upstream panel {
  server panel:8000;
}

upstream back-office  {
  server back-office:1337;
}

upstream bot  {
  server bot:3000;
}

server {
  listen 80;
  
  location = / {
    proxy_pass http://panel;
  }
#   location /panel-users {
#     proxy_pass http://panel;
#   }
#   location /broadcast {
#     proxy_pass http://panel;
#   }
#   location /history {
#     proxy_pass http://panel;
#   }
#   location /change {
#     proxy_pass http://panel;
#   }
  location /sockjs-node {
    proxy_pass http://panel;
  }
      location /panel {
          rewrite ^/panel(/.*)$ $1 break;
        proxy_pass http://panel;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass_request_headers on;
    }

    location /bot {
          rewrite ^/bot(/.*)$ $1 break;
        proxy_pass http://bot;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass_request_headers on;
    }


      # Strapi API and Admin
    location / {
        proxy_pass http://back-office;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass_request_headers on;
    }
}